package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;

@SuppressWarnings("serial")
public class ConfirmacionVoto extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Embedded embedded_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ConfirmacionVoto() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		button_1.addListener(new Button.ClickListener() {
					
					@Override
					public void buttonClick(ClickEvent event) {
						// TODO Auto-generated method stub
						MyVaadinUI.getCurrent();
					}
			});
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("669px");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("669px");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("330px");
		label_1.setHeight("20px");
		label_1.setValue("¡Su voto ha sido registrado con exito!");
		mainLayout.addComponent(label_1, "top:100.0px;left:250.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Continuar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:180.0px;left:296.0px;");
		
		// embedded_2
		embedded_2 = new Embedded();
		embedded_2.setImmediate(false);
		embedded_2.setWidth("-1px");
		embedded_2.setHeight("-1px");
		embedded_2
				.setSource(new ExternalResource(
						"http://24.media.tumblr.com/tumblr_md2xuxGz2p1qz8fd8o1_r1_400.gif"));
		embedded_2.setType(1);
		embedded_2.setMimeType("image/png");
		mainLayout.addComponent(embedded_2, "top:237.0px;left:260.0px;");
		
		return mainLayout;
	}

}
