package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Window;

@SuppressWarnings("serial")
public class CrearEvento extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private CrearPlebiscito crearPlebiscito_2;
	@AutoGenerated
	private CrearEleccion crearEleccion_1;
	Window crearEleccion = null;
	Window crearPlebiscito = null;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public CrearEvento() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1,
				"top:32.0px;right:0.0px;bottom:91.0px;left:0.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Seleccione el tipo de evento que desea:");
		mainLayout.addComponent(label_2, "top:10.0px;left:6.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// crearEleccion_1
		crearEleccion_1 = new CrearEleccion();
		crearEleccion_1.setImmediate(false);
		crearEleccion_1.setWidth("800px");
		crearEleccion_1.setHeight("600px");
		tabSheet_1.addTab(crearEleccion_1, "Crear una Elección", null);
		
		// crearPlebiscito_2
		crearPlebiscito_2 = new CrearPlebiscito();
		crearPlebiscito_2.setImmediate(false);
		crearPlebiscito_2.setWidth("800px");
		crearPlebiscito_2.setHeight("600px");
		tabSheet_1.addTab(crearPlebiscito_2, "Crear un Plebiscito", null);
		
		return tabSheet_1;
	}

}
