package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;

@SuppressWarnings("serial")
public class RecibirVotoEleccion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Embedded embedded_1;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private Label label_1;
	private Conexion conexion;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RecibirVotoEleccion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		String consulta = "SELECT nombre, informacion, id_tendencia FROM tendencia;";
		 conexion = new Conexion("rebeca", "ramirez.arroyo");
		 if(conexion!=null){
			  final SQLContainer resultado = conexion.consulta(consulta);
			  if(resultado != null){
			  comboBox_1.setInputPrompt("Seleccione una tendencia");
			  comboBox_1.setContainerDataSource(resultado);
			  comboBox_1.setItemCaptionPropertyId("nombre");
			  
			  button_1.addClickListener(new Button.ClickListener() {
				
				@Override
				public void buttonClick(ClickEvent event) {
					// TODO Auto-generated method stub
					final Item item = comboBox_1.getItem(comboBox_1.getValue());
					String info = item.getItemProperty("informacion").toString();
					final String idtend= item.getItemProperty("id_tendencia").toString();
					textArea_1.setValue(info);
					final int idtende= Integer.parseInt(idtend);
					
					
					button_2.addListener(new Button.ClickListener() {
						
						@Override
						public void buttonClick(ClickEvent event) {
							// TODO Auto-generated method stub
							//String nombre = item.getItemProperty("nombre").toString();
							//Hacer consulta para agregar voto a la tendencia
							

							 String consulta = "SELECT votos_recibidos FROM resultados_eleccion WHERE id_tendencia="+idtende+";";//&& id_evento=idEvento
							 conexion = new Conexion("rebeca", "ramirez.arroyo");
							 if(conexion!=null){
								  SQLContainer resultado2 = conexion.consulta(consulta);
								  if(resultado2 != null){
									  resultado2.firstItemId();
									  Item item2 = resultado2.getItem(resultado.firstItemId());
									  String votos = item2.getItemProperty("votos_recibidos").toString();
									  int votosTot = Integer.parseInt(votos);
									  votosTot++;
									  
									  sumarVoto(votosTot, idtende);
									  
									  
									  
								  }
							 }
							 
							 
							 
						}
					});
					
					
					
				}
			});
			  
		     }
		 }
	}
	
	private  void sumarVoto(int votos, int id){
		String consulta = "UPDATE resultados_eleccion SET votos_recibidos="+votos+" WHERE id_tendencia="+id+";";
		   conexion = new Conexion("rebeca", "ramirez.arroyo");
		   if(conexion.ejecutar(consulta)){
			   label_2.setValue("Se realizo su voto correctamente");
			   MyVaadinUI.getCurrent().setContent(new ConfirmacionVoto());
		   }
	}
	
	private void getIdEvento(int id){ 
		//llama a clase que tiene el id
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("737px");
		mainLayout.setHeight("480px");
		
		// top-level component properties
		setWidth("737px");
		setHeight("480px");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Escoger partido");
		mainLayout.addComponent(label_1, "top:20.0px;left:60.0px;");
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		mainLayout.addComponent(comboBox_1, "top:60.0px;left:80.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Buscar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:60.0px;left:280.0px;");
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("420px");
		textArea_1.setHeight("140px");
		mainLayout.addComponent(textArea_1, "top:120.0px;left:40.0px;");
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Votar por este partido");
		button_2.setImmediate(true);
		button_2.setWidth("320px");
		button_2.setHeight("-1px");
		mainLayout.addComponent(button_2, "top:280.0px;left:100.0px;");
		
		// button_3
		button_3 = new Button();
		button_3.setCaption("Votar NULO");
		button_3.setImmediate(true);
		button_3.setWidth("100.0%");
		button_3.setHeight("-1px");
		mainLayout.addComponent(button_3,
				"top:320.0px;right:297.0px;left:93.0px;");
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("Ver resultados hasta el momento");
		button_5.setImmediate(true);
		button_5.setWidth("-1px");
		button_5.setHeight("-1px");
		mainLayout.addComponent(button_5, "top:380.0px;left:140.0px;");
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("250px");
		embedded_1.setHeight("254px");
		embedded_1.setSource(new ExternalResource(
				"http://schoolboardelection.com/VOTING.BOOTH.ANIMATION.gif"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		mainLayout.addComponent(embedded_1, "top:86.0px;left:480.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Resultado");
		mainLayout.addComponent(label_2, "top:382.0px;left:493.0px;");
		
		return mainLayout;
	}

}
