package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;

@SuppressWarnings("serial")
public class RecibirVotoPlebiscito extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Embedded embedded_1;
	@AutoGenerated
	private Button button_4;
	@AutoGenerated
	private Button button_3;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private Label label_2;
	private Conexion conexion;
	private int idEvento;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public RecibirVotoPlebiscito() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here

		String consulta = "SELECT nombre, informacion, id_tendencia FROM tendencia;";
		conexion = new Conexion("rebeca", "ramirez.arroyo");
		if (conexion != null) {
			final SQLContainer resultado = conexion.consulta(consulta);
			if (resultado != null) {
				comboBox_1.setInputPrompt("Seleccione una tendencia");
				comboBox_1.setContainerDataSource(resultado);
				comboBox_1.setItemCaptionPropertyId("nombre");

				button_1.addClickListener(new Button.ClickListener() {

					@Override
					public void buttonClick(ClickEvent event) {
						// TODO Auto-generated method stub
						final Item item = comboBox_1.getItem(comboBox_1
								.getValue());
						String info = item.getItemProperty("informacion")
								.toString();
						final String idtend = item.getItemProperty(
								"id_tendencia").toString();
						textArea_1.setValue(info);
						final int idtende = Integer.parseInt(idtend);

						button_2.addListener(new Button.ClickListener() {

							@Override
							public void buttonClick(ClickEvent event) {
								// TODO Auto-generated method stub
								// String nombre =
								// item.getItemProperty("nombre").toString();
								// Hacer consulta para agregar voto a la
								// tendencia

								String consulta = "SELECT votos_recibidos FROM resultados_plebiscito WHERE id_tendencia="
										+ idtende + ";";// && id_evento=idEvento
								conexion = new Conexion("rebeca", "ramirez.arroyo");
								if (conexion != null) {
									SQLContainer resultado2 = conexion.consulta(consulta);
									if (resultado2 != null) {
										resultado2.firstItemId();
										Item item2 = resultado2.getItem(resultado.firstItemId());
										String votos = item2.getItemProperty("votos_recibidos").toString();
										int votosTot = Integer.parseInt(votos);
										votosTot++;

										sumarVoto(votosTot, idtende);
									}
								}
							}
						});
					}
				});
			}
		}

		MyVaadinUI.getCurrent();

	}

	private void sumarVoto(int votos, int id) {
		String consulta = "UPDATE resultados_plebiscito SET votos_recibidos="
				+ votos + " WHERE id_tendencia=" + id + ";";
		conexion = new Conexion("rebeca", "ramirez.arroyo");
		if (conexion.ejecutar(consulta)) {
			label_4.setValue("Se realizo su voto correctamente");
			MyVaadinUI.getCurrent().setContent(new ConfirmacionVoto());
		}
	}

	private void getIdEvento(int id) {
		// llama a clase que tiene el id
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setCaption("Resultado");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("860px");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("860px");
		setHeight("100.0%");

		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Escoger tendencia");
		mainLayout.addComponent(label_2, "top:120.0px;left:64.0px;");

		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("178px");
		comboBox_1.setHeight("-1px");
		mainLayout.addComponent(comboBox_1, "top:160.0px;left:82.0px;");

		// button_2
		button_2 = new Button();
		button_2.setCaption("Votar por este plebiscito");
		button_2.setImmediate(true);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		mainLayout.addComponent(button_2, "top:354.0px;left:200.0px;");

		// button_3
		button_3 = new Button();
		button_3.setCaption("Votar NULO");
		button_3.setImmediate(true);
		button_3.setWidth("-1px");
		button_3.setHeight("-1px");
		mainLayout.addComponent(button_3, "top:394.0px;left:230.0px;");

		// button_4
		button_4 = new Button();
		button_4.setCaption("Ver resultados hasta el momento");
		button_4.setImmediate(true);
		button_4.setWidth("-1px");
		button_4.setHeight("-1px");
		mainLayout.addComponent(button_4, "top:454.0px;left:167.0px;");

		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("250px");
		embedded_1.setHeight("254px");
		embedded_1.setSource(new ExternalResource(
				"http://schoolboardelection.com/VOTING.BOOTH.ANIMATION.gif"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		mainLayout.addComponent(embedded_1, "top:100.0px;left:480.0px;");

		// button_1
		button_1 = new Button();
		button_1.setCaption("Buscar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:154.0px;left:300.0px;");

		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("332px");
		textArea_1.setHeight("100px");
		mainLayout.addComponent(textArea_1, "top:200.0px;left:108.0px;");

		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Resultado");
		mainLayout.addComponent(label_4, "top:420.0px;left:560.0px;");

		return mainLayout;
	}

}
