package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Upload;

@SuppressWarnings("serial")
public class ventanaFirmaDigital extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Upload upload_1;
	private Label label_1;
	final private Uploader up = new Uploader();
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ventanaFirmaDigital() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		label_1 = new Label("<b><font color=\"003399\"><div style='font-size: 10px'><h1>Suba el archivo con su llave privada</h1></div></font></b>", Label.CONTENT_XHTML);	
		mainLayout.addComponent(label_1, "top:20.0px;left:31.0px;");
		upload_1.setButtonCaption("Subir llave");
		upload_1.setReceiver(up);
		upload_1.addListener(up);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("560px");
		mainLayout.setHeight("200px");
		
		// top-level component properties
		setWidth("560px");
		setHeight("200px");
		
		// upload_1
		upload_1 = new Upload();
		upload_1.setImmediate(false);
		upload_1.setWidth("-1px");
		upload_1.setHeight("-1px");
		mainLayout.addComponent(upload_1, "top:114.0px;left:84.0px;");
		
		return mainLayout;
	}

}
