package Inge2.voto_virtual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.Theme;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
@Theme("tema_voto_virtual")
public class VentanaLogin extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private PasswordField passwordField_1;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Embedded embedded_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VentanaLogin() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		textField_1.focus();
		textField_1.setTabIndex(1);
		passwordField_1.setTabIndex(2);
		button_1.setClickShortcut(KeyCode.ENTER);
		button_1.addClickListener(new Button.ClickListener() {
		    public void buttonClick(ClickEvent event) {
		    	comprobarUsuario();
		    }
		});
	}

	private void comprobarUsuario(){
		String usuario = textField_1.getValue();
		String password = passwordField_1.getValue();
//		Conexion con = new Conexion();
		if(usuario.equals("me") && password.equals("to")){ //if(user&&pass correctos)
			MyVaadinUI.getCurrent().setContent(new VentanaPrincipal());
		}else{
			label_3.setValue("Usuario o contraseña incorrecto");
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// embedded_1
		embedded_1 = new Embedded();
		embedded_1.setImmediate(false);
		embedded_1.setWidth("140px");
		embedded_1.setHeight("146px");
		embedded_1.setSource(new ThemeResource("img/login.png"));
		embedded_1.setType(1);
		embedded_1.setMimeType("image/png");
		mainLayout.addComponent(embedded_1, "top:254.0px;left:244.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("80px");
		label_1.setHeight("14px");
		label_1.setValue("USUARIO:");
		mainLayout.addComponent(label_1, "top:260.0px;left:404.0px;");
		
		// passwordField_1
		passwordField_1 = new PasswordField();
		passwordField_1.setImmediate(false);
		passwordField_1.setWidth("-1px");
		passwordField_1.setHeight("-1px");
		mainLayout.addComponent(passwordField_1, "top:336.0px;left:404.0px;");
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		mainLayout.addComponent(textField_1, "top:280.0px;left:404.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("CONTRASEÑA:");
		mainLayout.addComponent(label_2, "top:320.0px;left:404.0px;");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Ingresar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1, "top:374.0px;left:404.0px;");
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("217px");
		label_3.setHeight("27px");
		label_3.setValue(" ");
		mainLayout.addComponent(label_3, "top:410.0px;left:400.0px;");
		
		return mainLayout;
	}

}
